-- Oracle schema for Workplace Wellness Survey responses.
-- Run this in the Oracle schema used by the application datasource.

CREATE TABLE workplace_wellness_response (
  response_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  company_name VARCHAR2(255),
  email VARCHAR2(255),
  phone VARCHAR2(100),
  submitted_on TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE workplace_wellness_answer (
  answer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  response_id NUMBER NOT NULL,
  section_name VARCHAR2(150) NOT NULL,
  question_key VARCHAR2(100) NOT NULL,
  question_label VARCHAR2(500) NOT NULL,
  answer_value CLOB NOT NULL,
  display_order NUMBER(10) NOT NULL,
  CONSTRAINT fk_ww_answer_response
    FOREIGN KEY (response_id)
    REFERENCES workplace_wellness_response (response_id)
    ON DELETE CASCADE
);

CREATE INDEX idx_ww_answer_response
  ON workplace_wellness_answer (response_id);

CREATE INDEX idx_ww_answer_question
  ON workplace_wellness_answer (question_key);

CREATE INDEX idx_ww_response_submitted
  ON workplace_wellness_response (submitted_on);
