-- Oracle schema for Workplace Wellness Survey responses.
-- Run this in the Oracle schema used by the application datasource.

CREATE TABLE workplace_wellness_response (
  response_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  company_name VARCHAR2(255),
  email VARCHAR2(255),
  phone VARCHAR2(100),
  submitted_on TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE workplace_wellness_answer (
  answer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  response_id NUMBER NOT NULL,
  section_name VARCHAR2(150) NOT NULL,
  question_key VARCHAR2(100) NOT NULL,
  question_label VARCHAR2(500) NOT NULL,
  answer_value CLOB NOT NULL,
  display_order NUMBER(10) NOT NULL,
  CONSTRAINT fk_ww_answer_response
    FOREIGN KEY (response_id)
    REFERENCES workplace_wellness_response (response_id)
    ON DELETE CASCADE
);

CREATE INDEX idx_ww_answer_response
  ON workplace_wellness_answer (response_id);

CREATE INDEX idx_ww_answer_question
  ON workplace_wellness_answer (question_key);

CREATE INDEX idx_ww_response_submitted
  ON workplace_wellness_response (submitted_on);

CREATE TABLE school_health_response (
  response_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  institution_name VARCHAR2(255),
  contact_email VARCHAR2(255),
  contact_phone VARCHAR2(100),
  submitted_on TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE school_health_answer (
  answer_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  response_id NUMBER NOT NULL,
  section_name VARCHAR2(150) NOT NULL,
  question_key VARCHAR2(100) NOT NULL,
  question_label VARCHAR2(500) NOT NULL,
  answer_value CLOB NOT NULL,
  display_order NUMBER(10) NOT NULL,
  CONSTRAINT fk_sh_answer_response
    FOREIGN KEY (response_id)
    REFERENCES school_health_response (response_id)
    ON DELETE CASCADE
);

CREATE INDEX idx_sh_answer_response
  ON school_health_answer (response_id);

CREATE INDEX idx_sh_answer_question
  ON school_health_answer (question_key);

CREATE INDEX idx_sh_response_submitted
  ON school_health_response (submitted_on);

CREATE TABLE school_health_question_text (
  question_key VARCHAR2(100) NOT NULL,
  locale_code VARCHAR2(10) NOT NULL,
  section_name VARCHAR2(150) NOT NULL,
  question_label VARCHAR2(500) NOT NULL,
  CONSTRAINT pk_sh_question_text PRIMARY KEY (question_key, locale_code)
);

CREATE TABLE school_health_option_text (
  option_group VARCHAR2(100) NOT NULL,
  option_value VARCHAR2(100) NOT NULL,
  locale_code VARCHAR2(10) NOT NULL,
  option_label VARCHAR2(500) NOT NULL,
  display_order NUMBER(10) NOT NULL,
  CONSTRAINT pk_sh_option_text PRIMARY KEY (option_group, option_value, locale_code)
);

CREATE TABLE SURVEY_DETAILS (
  ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  EVENT_UUID VARCHAR2(100),
  SURVEY_HEADING_ID NUMBER,
  SURVEY_HEADING VARCHAR2(255),
  SURVEY_QNS VARCHAR2(1000),
  FIELD_TYPE VARCHAR2(50),
  IS_MANDATORY NUMBER(1) DEFAULT 0 NOT NULL,
  FIELD_OPTION VARCHAR2(100),
  REQUIRED_MESSAGE VARCHAR2(500),
  PRE_SURVEY NUMBER(1) DEFAULT 0 NOT NULL,
  POST_SURVEY NUMBER(1) DEFAULT 0 NOT NULL,
  CORRECT_ANSWER_ID NUMBER,
  SURVEY_HEADING_AR VARCHAR2(255),
  SURVEY_QNS_AR VARCHAR2(1000),
  REQUIRED_MESSAGE_AR VARCHAR2(500)
);

CREATE TABLE OPTIONS (
  ID NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  DESCRIPTION VARCHAR2(500),
  DESCRIPTION_AR VARCHAR2(500),
  EVENT_UUID VARCHAR2(100),
  OPTION_TYPE VARCHAR2(100)
);
