/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.89
 * Generated at: 2026-02-20 10:51:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class topicquestions_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/javax.faces-2.2.20.jar", Long.valueOf(1771582098000L));
    _jspx_dependants.put("/menu.jsp", Long.valueOf(1771581538000L));
    _jspx_dependants.put("jar:file:/C:/Users/atul3/Downloads/jobapplication-primefaces/jobapplication-primefaces/online-survey-system-java/.tools/apache-tomcat-9.0.89/webapps/surveyadmin/WEB-INF/lib/javax.faces-2.2.20.jar!/META-INF/jsf_core.tld", Long.valueOf(1564549022000L));
    _jspx_dependants.put("/header.html", Long.valueOf(1771581538000L));
    _jspx_dependants.put("jar:file:/C:/Users/atul3/Downloads/jobapplication-primefaces/jobapplication-primefaces/online-survey-system-java/.tools/apache-tomcat-9.0.89/webapps/surveyadmin/WEB-INF/lib/javax.faces-2.2.20.jar!/META-INF/html_basic.tld", Long.valueOf(1564549022000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fform_0026_005fid;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fdataTable_0026_005fwidth_005fvar_005fvalue_005fborder;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005fcolumn;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fverbatim;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fh_005foutputLink_0026_005fvalue_005fonclick;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ff_005fparam_0026_005fvalue_005fname_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ff_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fform_0026_005fid = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fdataTable_0026_005fwidth_005fvar_005fvalue_005fborder = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005fcolumn = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fverbatim = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fh_005foutputLink_0026_005fvalue_005fonclick = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ff_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ff_005fview.release();
    _005fjspx_005ftagPool_005fh_005fform_0026_005fid.release();
    _005fjspx_005ftagPool_005fh_005fdataTable_0026_005fwidth_005fvar_005fvalue_005fborder.release();
    _005fjspx_005ftagPool_005fh_005fcolumn.release();
    _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.release();
    _005fjspx_005ftagPool_005ff_005fverbatim.release();
    _005fjspx_005ftagPool_005fh_005foutputText_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fh_005foutputLink_0026_005fvalue_005fonclick.release();
    _005fjspx_005ftagPool_005ff_005fparam_0026_005fvalue_005fname_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\"\r\n");
      out.write("    \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      if (_jspx_meth_f_005fview_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_f_005fview_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:view
    com.sun.faces.taglib.jsf_core.ViewTag _jspx_th_f_005fview_005f0 = new com.sun.faces.taglib.jsf_core.ViewTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fview_005f0);
    try {
      _jspx_th_f_005fview_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fview_005f0.setParent(null);
      _jspx_th_f_005fview_005f0.setJspId("jsp_26273596_0");
      int _jspx_eval_f_005fview_005f0 = _jspx_th_f_005fview_005f0.doStartTag();
      if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fview_005f0);
        }
        do {
          out.write("\r\n");
          out.write("    <html>\r\n");
          out.write("        <head>\r\n");
          out.write("            <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\"/>\r\n");
          out.write("            <link rel=\"stylesheet\" href=\"styles.css\" />\r\n");
          out.write("            <title>Add Topic</title>\r\n");
          out.write("        </head>\r\n");
          out.write("        <body>\r\n");
          out.write("            ");
          if (_jspx_meth_h_005fform_005f0(_jspx_th_f_005fview_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("        </body>\r\n");
          out.write("    </html>\r\n");
          int evalDoAfterBody = _jspx_th_f_005fview_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fview_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fform_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:form
    com.sun.faces.taglib.html_basic.FormTag _jspx_th_h_005fform_005f0 = new com.sun.faces.taglib.html_basic.FormTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fform_005f0);
    try {
      _jspx_th_h_005fform_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fform_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005fview_005f0);
      // /topicquestions.jsp(16,12) name = id type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005fform_005f0.setId("addTopicForm");
      _jspx_th_h_005fform_005f0.setJspId("jsp_26273596_1");
      int _jspx_eval_h_005fform_005f0 = _jspx_th_h_005fform_005f0.doStartTag();
      if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fform_005f0);
        }
        do {
          out.write("\r\n");
          out.write("                ");
          out.write("<div class=\"header\">Survey Admin </div>");
          out.write("\r\n");
          out.write("                <table  style=\"width:100%;height:600px\">\r\n");
          out.write("                    <tr>\r\n");
          out.write("                        <td class=\"menu\">\r\n");
          out.write("                            ");
          out.write("<h4>User  : ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sessionScope.uname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</h4>\r\n");
          out.write("<a href=\"logout.jsp\">Logout</a>\r\n");
          out.write("<p/>\r\n");
          out.write("&nbsp;\r\n");
          out.write("<p/>\r\n");
          out.write("<a href=\"home.jsp\">Home</a>\r\n");
          out.write("<p/>\r\n");
          out.write("<a href=\"home.jsp\">List Topics</a>\r\n");
          out.write("<p/>\r\n");
          out.write("<a href=\"addtopic.jsp\">Add New Topic</a>\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("\r\n");
          out.write("                        </td>\r\n");
          out.write("                        <td style=\"vertical-align: top\">\r\n");
          out.write("                            <h2>Topics</h2>\r\n");
          out.write("                                    ");
          if (_jspx_meth_h_005fdataTable_005f0(_jspx_th_h_005fform_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                </td>\r\n");
          out.write("                        </tr>\r\n");
          out.write("                </table>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_h_005fform_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fform_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fform_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fform_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fdataTable_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fform_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:dataTable
    com.sun.faces.taglib.html_basic.DataTableTag _jspx_th_h_005fdataTable_005f0 = new com.sun.faces.taglib.html_basic.DataTableTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fdataTable_005f0);
    try {
      _jspx_th_h_005fdataTable_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fdataTable_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fform_005f0);
      // /topicquestions.jsp(25,36) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(25,36) '#{topic.questions}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{topic.questions}",java.lang.Object.class)));
      // /topicquestions.jsp(25,36) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setVar("question");
      // /topicquestions.jsp(25,36) name = border type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = int deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setBorder(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(25,36) '1'",_jsp_getExpressionFactory().createValueExpression("1",int.class)));
      // /topicquestions.jsp(25,36) name = width type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005fdataTable_005f0.setWidth(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(25,36) '100%'",_jsp_getExpressionFactory().createValueExpression("100%",java.lang.String.class)));
      _jspx_th_h_005fdataTable_005f0.setJspId("jsp_26273596_2");
      int _jspx_eval_h_005fdataTable_005f0 = _jspx_th_h_005fdataTable_005f0.doStartTag();
      if (_jspx_eval_h_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fdataTable_005f0);
        }
        do {
          out.write("\r\n");
          out.write("                                        ");
          if (_jspx_meth_h_005fcolumn_005f0(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          if (_jspx_meth_h_005fcolumn_005f1(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          if (_jspx_meth_h_005fcolumn_005f2(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_h_005fcolumn_005f3(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          if (_jspx_meth_h_005fcolumn_005f4(_jspx_th_h_005fdataTable_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                    ");
          int evalDoAfterBody = _jspx_th_h_005fdataTable_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fdataTable_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fdataTable_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fdataTable_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f0 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f0);
    try {
      _jspx_th_h_005fcolumn_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f0.setJspId("jsp_26273596_3");
      int _jspx_eval_h_005fcolumn_005f0 = _jspx_th_h_005fcolumn_005f0.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f0);
        }
        do {
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_f_005ffacet_005f0(_jspx_th_h_005fcolumn_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_h_005foutputText_005f0(_jspx_th_h_005fcolumn_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f0 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f0_reused = false;
    try {
      _jspx_th_f_005ffacet_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f0);
      // /topicquestions.jsp(27,44) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f0.setName("header");
      int _jspx_eval_f_005ffacet_005f0 = _jspx_th_f_005ffacet_005f0.doStartTag();
      if (_jspx_eval_f_005ffacet_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          if (_jspx_meth_f_005fverbatim_005f0(_jspx_th_f_005ffacet_005f0, _jspx_page_context))
            return true;
          out.write(' ');
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f0);
      _jspx_th_f_005ffacet_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f0, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fverbatim_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:verbatim
    com.sun.faces.taglib.jsf_core.VerbatimTag _jspx_th_f_005fverbatim_005f0 = new com.sun.faces.taglib.jsf_core.VerbatimTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fverbatim_005f0);
    try {
      _jspx_th_f_005fverbatim_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fverbatim_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f0);
      _jspx_th_f_005fverbatim_005f0.setJspId("jsp_26273596_4");
      int _jspx_eval_f_005fverbatim_005f0 = _jspx_th_f_005fverbatim_005f0.doStartTag();
      if (_jspx_eval_f_005fverbatim_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fverbatim_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fverbatim_005f0);
        }
        do {
          out.write("Question");
          int evalDoAfterBody = _jspx_th_f_005fverbatim_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fverbatim_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fverbatim_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fverbatim_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f0 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f0);
    try {
      _jspx_th_h_005foutputText_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f0);
      // /topicquestions.jsp(28,44) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(28,44) '#{question.text}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{question.text}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f0.setJspId("jsp_26273596_5");
      int _jspx_eval_h_005foutputText_005f0 = _jspx_th_h_005foutputText_005f0.doStartTag();
      if (_jspx_th_h_005foutputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f1 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f1);
    try {
      _jspx_th_h_005fcolumn_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f1.setJspId("jsp_26273596_6");
      int _jspx_eval_h_005fcolumn_005f1 = _jspx_th_h_005fcolumn_005f1.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f1);
        }
        do {
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_f_005ffacet_005f1(_jspx_th_h_005fcolumn_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_h_005foutputText_005f1(_jspx_th_h_005fcolumn_005f1, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f1 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f1_reused = false;
    try {
      _jspx_th_f_005ffacet_005f1.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f1);
      // /topicquestions.jsp(31,44) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f1.setName("header");
      int _jspx_eval_f_005ffacet_005f1 = _jspx_th_f_005ffacet_005f1.doStartTag();
      if (_jspx_eval_f_005ffacet_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          if (_jspx_meth_f_005fverbatim_005f1(_jspx_th_f_005ffacet_005f1, _jspx_page_context))
            return true;
          out.write(' ');
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f1);
      _jspx_th_f_005ffacet_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f1, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fverbatim_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:verbatim
    com.sun.faces.taglib.jsf_core.VerbatimTag _jspx_th_f_005fverbatim_005f1 = new com.sun.faces.taglib.jsf_core.VerbatimTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fverbatim_005f1);
    try {
      _jspx_th_f_005fverbatim_005f1.setPageContext(_jspx_page_context);
      _jspx_th_f_005fverbatim_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f1);
      _jspx_th_f_005fverbatim_005f1.setJspId("jsp_26273596_7");
      int _jspx_eval_f_005fverbatim_005f1 = _jspx_th_f_005fverbatim_005f1.doStartTag();
      if (_jspx_eval_f_005fverbatim_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fverbatim_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fverbatim_005f1);
        }
        do {
          out.write("Option1");
          int evalDoAfterBody = _jspx_th_f_005fverbatim_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fverbatim_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fverbatim_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fverbatim_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f1 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f1);
    try {
      _jspx_th_h_005foutputText_005f1.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f1);
      // /topicquestions.jsp(32,44) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(32,44) '#{question.opt1}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{question.opt1}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f1.setJspId("jsp_26273596_8");
      int _jspx_eval_h_005foutputText_005f1 = _jspx_th_h_005foutputText_005f1.doStartTag();
      if (_jspx_th_h_005foutputText_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f1, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f2 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f2);
    try {
      _jspx_th_h_005fcolumn_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f2.setJspId("jsp_26273596_9");
      int _jspx_eval_h_005fcolumn_005f2 = _jspx_th_h_005fcolumn_005f2.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f2);
        }
        do {
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_f_005ffacet_005f2(_jspx_th_h_005fcolumn_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_h_005foutputText_005f2(_jspx_th_h_005fcolumn_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f2 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f2_reused = false;
    try {
      _jspx_th_f_005ffacet_005f2.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f2);
      // /topicquestions.jsp(35,44) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f2.setName("header");
      int _jspx_eval_f_005ffacet_005f2 = _jspx_th_f_005ffacet_005f2.doStartTag();
      if (_jspx_eval_f_005ffacet_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          if (_jspx_meth_f_005fverbatim_005f2(_jspx_th_f_005ffacet_005f2, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f2);
      _jspx_th_f_005ffacet_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f2, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fverbatim_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:verbatim
    com.sun.faces.taglib.jsf_core.VerbatimTag _jspx_th_f_005fverbatim_005f2 = new com.sun.faces.taglib.jsf_core.VerbatimTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fverbatim_005f2);
    try {
      _jspx_th_f_005fverbatim_005f2.setPageContext(_jspx_page_context);
      _jspx_th_f_005fverbatim_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f2);
      _jspx_th_f_005fverbatim_005f2.setJspId("jsp_26273596_10");
      int _jspx_eval_f_005fverbatim_005f2 = _jspx_th_f_005fverbatim_005f2.doStartTag();
      if (_jspx_eval_f_005fverbatim_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fverbatim_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fverbatim_005f2);
        }
        do {
          out.write("Option2");
          int evalDoAfterBody = _jspx_th_f_005fverbatim_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fverbatim_005f2 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fverbatim_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fverbatim_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f2 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f2);
    try {
      _jspx_th_h_005foutputText_005f2.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f2);
      // /topicquestions.jsp(37,44) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(37,44) '#{question.opt2}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{question.opt2}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f2.setJspId("jsp_26273596_11");
      int _jspx_eval_h_005foutputText_005f2 = _jspx_th_h_005foutputText_005f2.doStartTag();
      if (_jspx_th_h_005foutputText_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f2, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f3 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f3);
    try {
      _jspx_th_h_005fcolumn_005f3.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f3.setJspId("jsp_26273596_12");
      int _jspx_eval_h_005fcolumn_005f3 = _jspx_th_h_005fcolumn_005f3.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f3);
        }
        do {
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_f_005ffacet_005f3(_jspx_th_h_005fcolumn_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_h_005foutputText_005f3(_jspx_th_h_005fcolumn_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f3 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f3_reused = false;
    try {
      _jspx_th_f_005ffacet_005f3.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f3);
      // /topicquestions.jsp(40,44) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f3.setName("header");
      int _jspx_eval_f_005ffacet_005f3 = _jspx_th_f_005ffacet_005f3.doStartTag();
      if (_jspx_eval_f_005ffacet_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          if (_jspx_meth_f_005fverbatim_005f3(_jspx_th_f_005ffacet_005f3, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f3);
      _jspx_th_f_005ffacet_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f3, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fverbatim_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:verbatim
    com.sun.faces.taglib.jsf_core.VerbatimTag _jspx_th_f_005fverbatim_005f3 = new com.sun.faces.taglib.jsf_core.VerbatimTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fverbatim_005f3);
    try {
      _jspx_th_f_005fverbatim_005f3.setPageContext(_jspx_page_context);
      _jspx_th_f_005fverbatim_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f3);
      _jspx_th_f_005fverbatim_005f3.setJspId("jsp_26273596_13");
      int _jspx_eval_f_005fverbatim_005f3 = _jspx_th_f_005fverbatim_005f3.doStartTag();
      if (_jspx_eval_f_005fverbatim_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fverbatim_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fverbatim_005f3);
        }
        do {
          out.write("Option3");
          int evalDoAfterBody = _jspx_th_f_005fverbatim_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fverbatim_005f3 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fverbatim_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fverbatim_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f3 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f3);
    try {
      _jspx_th_h_005foutputText_005f3.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f3);
      // /topicquestions.jsp(42,44) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f3.setValue(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(42,44) '#{question.opt3}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{question.opt3}",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f3.setJspId("jsp_26273596_14");
      int _jspx_eval_h_005foutputText_005f3 = _jspx_th_h_005foutputText_005f3.doStartTag();
      if (_jspx_th_h_005foutputText_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f3, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005fcolumn_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fdataTable_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:column
    com.sun.faces.taglib.html_basic.ColumnTag _jspx_th_h_005fcolumn_005f4 = new com.sun.faces.taglib.html_basic.ColumnTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005fcolumn_005f4);
    try {
      _jspx_th_h_005fcolumn_005f4.setPageContext(_jspx_page_context);
      _jspx_th_h_005fcolumn_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fdataTable_005f0);
      _jspx_th_h_005fcolumn_005f4.setJspId("jsp_26273596_15");
      int _jspx_eval_h_005fcolumn_005f4 = _jspx_th_h_005fcolumn_005f4.doStartTag();
      if (_jspx_eval_h_005fcolumn_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005fcolumn_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005fcolumn_005f4);
        }
        do {
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_f_005ffacet_005f4(_jspx_th_h_005fcolumn_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          if (_jspx_meth_h_005foutputLink_005f0(_jspx_th_h_005fcolumn_005f4, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                        ");
          int evalDoAfterBody = _jspx_th_h_005fcolumn_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005fcolumn_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005fcolumn_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005fcolumn_005f4, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005ffacet_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:facet
    javax.faces.webapp.FacetTag _jspx_th_f_005ffacet_005f4 = (javax.faces.webapp.FacetTag) _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.get(javax.faces.webapp.FacetTag.class);
    boolean _jspx_th_f_005ffacet_005f4_reused = false;
    try {
      _jspx_th_f_005ffacet_005f4.setPageContext(_jspx_page_context);
      _jspx_th_f_005ffacet_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f4);
      // /topicquestions.jsp(45,44) name = name type = java.lang.String reqTime = false required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_f_005ffacet_005f4.setName("header");
      int _jspx_eval_f_005ffacet_005f4 = _jspx_th_f_005ffacet_005f4.doStartTag();
      if (_jspx_eval_f_005ffacet_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write(' ');
          if (_jspx_meth_f_005fverbatim_005f4(_jspx_th_f_005ffacet_005f4, _jspx_page_context))
            return true;
          out.write(' ');
          int evalDoAfterBody = _jspx_th_f_005ffacet_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_f_005ffacet_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ff_005ffacet_0026_005fname.reuse(_jspx_th_f_005ffacet_005f4);
      _jspx_th_f_005ffacet_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005ffacet_005f4, _jsp_getInstanceManager(), _jspx_th_f_005ffacet_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fverbatim_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_f_005ffacet_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:verbatim
    com.sun.faces.taglib.jsf_core.VerbatimTag _jspx_th_f_005fverbatim_005f4 = new com.sun.faces.taglib.jsf_core.VerbatimTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fverbatim_005f4);
    try {
      _jspx_th_f_005fverbatim_005f4.setPageContext(_jspx_page_context);
      _jspx_th_f_005fverbatim_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_f_005ffacet_005f4);
      _jspx_th_f_005fverbatim_005f4.setJspId("jsp_26273596_16");
      int _jspx_eval_f_005fverbatim_005f4 = _jspx_th_f_005fverbatim_005f4.doStartTag();
      if (_jspx_eval_f_005fverbatim_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_f_005fverbatim_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_f_005fverbatim_005f4);
        }
        do {
          out.write("&nbsp;");
          int evalDoAfterBody = _jspx_th_f_005fverbatim_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_f_005fverbatim_005f4 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_f_005fverbatim_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fverbatim_005f4, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputLink_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005fcolumn_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputLink
    com.sun.faces.taglib.html_basic.OutputLinkTag _jspx_th_h_005foutputLink_005f0 = new com.sun.faces.taglib.html_basic.OutputLinkTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputLink_005f0);
    try {
      _jspx_th_h_005foutputLink_005f0.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputLink_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005fcolumn_005f4);
      // /topicquestions.jsp(46,44) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLink_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(46,44) 'deletequestion.jsp'",_jsp_getExpressionFactory().createValueExpression("deletequestion.jsp",java.lang.Object.class)));
      // /topicquestions.jsp(46,44) name = onclick type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputLink_005f0.setOnclick(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(46,44) 'return confirm('Do you want to delete question?','Confirmation')'",_jsp_getExpressionFactory().createValueExpression("return confirm('Do you want to delete question?','Confirmation')",java.lang.String.class)));
      _jspx_th_h_005foutputLink_005f0.setJspId("jsp_26273596_17");
      int _jspx_eval_h_005foutputLink_005f0 = _jspx_th_h_005foutputLink_005f0.doStartTag();
      if (_jspx_eval_h_005foutputLink_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_h_005foutputLink_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_h_005foutputLink_005f0);
        }
        do {
          out.write("\r\n");
          out.write("                                                ");
          if (_jspx_meth_h_005foutputText_005f4(_jspx_th_h_005foutputLink_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                                ");
          if (_jspx_meth_f_005fparam_005f0(_jspx_th_h_005foutputLink_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("                                            ");
          int evalDoAfterBody = _jspx_th_h_005foutputLink_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_h_005foutputLink_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_h_005foutputLink_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputLink_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_h_005foutputText_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005foutputLink_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  h:outputText
    com.sun.faces.taglib.html_basic.OutputTextTag _jspx_th_h_005foutputText_005f4 = new com.sun.faces.taglib.html_basic.OutputTextTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_h_005foutputText_005f4);
    try {
      _jspx_th_h_005foutputText_005f4.setPageContext(_jspx_page_context);
      _jspx_th_h_005foutputText_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005foutputLink_005f0);
      // /topicquestions.jsp(47,48) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_h_005foutputText_005f4.setValue(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(47,48) 'Delete'",_jsp_getExpressionFactory().createValueExpression("Delete",java.lang.Object.class)));
      _jspx_th_h_005foutputText_005f4.setJspId("jsp_26273596_18");
      int _jspx_eval_h_005foutputText_005f4 = _jspx_th_h_005foutputText_005f4.doStartTag();
      if (_jspx_th_h_005foutputText_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_h_005foutputText_005f4, _jsp_getInstanceManager(), false);
    }
    return false;
  }

  private boolean _jspx_meth_f_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_h_005foutputLink_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  f:param
    com.sun.faces.taglib.jsf_core.ParameterTag _jspx_th_f_005fparam_005f0 = new com.sun.faces.taglib.jsf_core.ParameterTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_f_005fparam_005f0);
    try {
      _jspx_th_f_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_f_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_h_005foutputLink_005f0);
      // /topicquestions.jsp(48,48) name = name type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
      _jspx_th_f_005fparam_005f0.setName(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(48,48) 'questionid'",_jsp_getExpressionFactory().createValueExpression("questionid",java.lang.String.class)));
      // /topicquestions.jsp(48,48) name = value type = javax.el.ValueExpression reqTime = false required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_f_005fparam_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/topicquestions.jsp(48,48) '#{question.id}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"#{question.id}",java.lang.Object.class)));
      _jspx_th_f_005fparam_005f0.setJspId("jsp_26273596_19");
      int _jspx_eval_f_005fparam_005f0 = _jspx_th_f_005fparam_005f0.doStartTag();
      if (_jspx_th_f_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_f_005fparam_005f0, _jsp_getInstanceManager(), false);
    }
    return false;
  }
}
